irq: export functions required by MFD_RP1
CONFIG_MFD_RP1 is tristate, but uses non-exported functions:

  ERROR: modpost: "msi_domain_set_affinity" [drivers/mfd/rp1.ko] undefined!
  ERROR: modpost: "irq_domain_deactivate_irq" [drivers/mfd/rp1.ko] undefined!
  ERROR: modpost: "irq_domain_activate_irq" [drivers/mfd/rp1.ko] undefined!
  make[4]: *** [scripts/Makefile.modpost:147: Module.symvers] Error 1
  make[3]: *** [Makefile:2000: modpost] Error 2

Seeing as all other RP1 drivers are tristate, export missing functions.

Signed-off-by: Ivan Shapovalov <intelfx@intelfx.name>